platform :ios, '8.0'
source 'https://github.com/C-Life/HETSDKSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
target :'HETOpenSDKDemo' do
    
   pod 'HETPublicSDK_WiFiModule/HF_LPT100_V3',     '1.0.0'
    pod 'WechatOpenSDK', '1.7.7'
    pod 'WeiboSDK', '3.1.3'
    pod 'TencentOpenApiSDK', '2.9.5'
    pod  'Masonry' ,'1.1.0'
    #pod  'SSZipArchive','1.1'
    pod 'HETOpenSDK','2.0.9'
    pod 'HETOpenSDK/HETMattressDeviceSDK'
end


inhibit_all_warnings!
